### ISSUE TITLE
Resource history api endpoint does not calculate the history correctly

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3302]
There resource history state endpoint does not calculate the history correctly. When the there are 7 active versions, all with the same desired state. It will return 4 items (shown in the web-console).

A database dump is [privately available.](https://inmanta.slack.com/archives/CKRF0C8R3/p1632840169108400?thread_ts=1632837365.102700&cid=CKRF0C8R3)

**Comment by andraskvr** [comment]
A possible cause is that the version range is not continuous, and the grouping of the history items expects it to be:

>  model |          attribute_hash          
> -------+----------------------------------
>   3782 | 61fe2f8cac8975a995fdc2d02165facb
>   3783 | 61fe2f8cac8975a995fdc2d02165facb
>   3785 | 61fe2f8cac8975a995fdc2d02165facb
>   3786 | 61fe2f8cac8975a995fdc2d02165facb
>   3788 | 61fe2f8cac8975a995fdc2d02165facb
>   3790 | 61fe2f8cac8975a995fdc2d02165facb
>   3791 | 61fe2f8cac8975a995fdc2d02165facb

Out of these 7 we get 4 because: `3782, 3783` are merged, `3784` is missing so `3785, 3786` are considered to be a new one, `3787` is missing again, so `3788` is also new, `3789` is missing, and the last 2 are grouped together.
The hash is all the same though, so it should be only one item.

**Comment by bartv** [comment]
When LSM is used, having holes in the versions is very common. Each validation compile will get a version but not a desired state
