### ISSUE TITLE
Allow implict indices in deeply nested structures: design

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#3540]
# Problem

In many models, writing them as a tree is most natural.
But the requirement that relations that are part of an index must be explicit in the constructor makes this difficult.

```
entity Family_bridge:
end
implement Family_bridge using std::none

entity Bridge_filter:
    string name
end
implement Bridge_filter using std::none

index Bridge_filter(family_bridge, name)

Bridge_filter.family_bridge [1] -- Family_bridge.bridge_filter [0:]


# Natural model, but not supported
# Family_bridge(
#     bridge_filter=Bridge_filter(
#         name="arp"
#     )
# )


# Required
bridge = Family_bridge(
)

filter = Bridge_filter(
    family_bridge=bridge,
    name="arp"
)
```

# Solution

We should allow statements that 

```
a.b=C()
```
becomes
`a.b=C(b_inv=a)`

 where b_inv is the inverse relation of b if C takes an argument b_inv

**Comment by sanderr** [comment]
As requested, my evaluation of how we could implement this. I see two approaches here. A semi concrete description follows below. I've explored these to the extent where I believe they're feasible but I haven't necessarily gotten all the details right yet.

# Compile-time injection
Right before the constructor gets emitted, attach runtime information to it. I think there are two relevant locations: `SetAttribute.resume` (`a.b = B()`) and `Constructor.execute` (`A(b=B())`). Both already have a small block of duplicate logic that we can separate and expand on: if the rhs `ExpressionStatement` is a constructor and its entity type has relation to the lhs entity type, inject the implicit lhs assignment. The constructor's `requires_emit` can then add these to the requires set and its `execute` can add them to the assignments.

Some refinement is still required here of course: we probably only want to add this implicit assignment if there's an index so we don't block the rhs constructor on the lhs instance unnecessarily.

## Injection strategy
To inject the implicit attributes into the `Constructor` AST node I think we once again have two options:
1. Set it on the AST node object: call `rhs.add_implicit_attribute(name, lhs: ResultVariable)`. I don't like the fact that it has state side effects on another AST node. It is a step away from the functional compiler that I think we one day want to move towards. That said, it is a very OO approach so there's nothing strictly fishy with it.
2. Extend `Constructor.requires_emit` with an optional parameter for the implicit attributes/assignments. `Constructor` itself would then be responsible for keeping required state. At the moment I think I prefer this approach but I haven't fully thought it through yet. I believe no additional state is actually required in this case because `requires_emit`'s return value contains everything `execute` needs.

# Early AST rewrite
Inspired by what you said yesterday, I believe the earliest point at which we have all required information available is at normalization time (by which I mean when the AST nodes' `normalize` methods get called). If I understand correctly at this point we already have full typing information available. `Constructor` obviously knows about the expression statements in its rhs and about its own type. `SetAttribute` on the other hand has no easy way to know about the type of its own instance at this point. If we go with this approach, I don't see how we could support `a.b = B()` but `A(b=B())` shouldn't be a problem.

# Evaluation
Considering the limitations of the early AST rewrite approach, if I'd have to make the call at this point I'd go with the compile-time injection via an optional parameter in `Constructor.requires_emit`. It's relatively simple, it fits the current compilation flow and with any luck it doesn't require keeping any dynamic state.

Let me know if anything isn't clear or if it is, let me know what you think.

**Comment by wouterdb** [comment]
We may be able to mix and match of these ideas:

1. all AST nodes get a method to receive implicit context of the form 'you are below a constructor of this type, the instance is bound to this name in the context`
2. during normalization, all constructors call this method on their children, allowing them to rewrite (could even be made functional)

It would additionally require every constructor to expose its instance as some kind of 'hidden' ResultVariable in the resolver used by all statements in the constructor. We could use the constructor object itself as the 'name' of the 'hidden' variable and we would need to construct an additional Resolver and ResultVariable for every constructor. 

We could make the rewrite method return during normalization if/which hidden variable is needed to prevent this overhead if it is not needed.

We can also, during this normalization step, check for mutual indices, which would make this optimization hang.

**Comment by wouterdb** [comment]
I think my idea could be considered something like

```
a = A(b=B(c=C())
```

becomes
```
a = $a := A(
  b = $b := B(
      a'=$a
      c = $c := C(
         a'= $a,
         b`=$b
      ),
   ),
)
```
(where a' is the reverse relation of a wrt ot the type of the constructor)

or even pull it up to the block level or use temp variables
```
a = $a
$a=A(b=$b)
$b=B(c=$C, a'=$a)
$c=C(a'=$a, b`=$b)
```
