### ISSUE TITLE
Wrong repo path leads to unclear error

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#3826]
When you include more than one `{}` in your repo path you will get an unclear error:

```bash
DEBUG    inmanta.module:module.py:286 could not clone repo
Traceback (most recent call last):
  File "/home/bart/dev/bics_ce/env/lib64/python3.6/site-packages/inmanta/module.py", line 279, in clone
    url = self.baseurl.format(name)
IndexError: tuple index out of range
```

This can happen for example when you forget the the repo separator is ` ` and not `:`

The indexerror can only happen in such a case and should be transformed in a clear error message.

- use replace '{}' instead of 'format'
- allow only one occurrence of '{}'

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/inmanta-core/3826?planning-poker) with ZenHub @arnaudsjs @bartv @FloLey @Hugo-Inmanta @sanderr

**Comment by Aditya1402** [comment]
Hello there! May I know if I can work on this issue? I'm a beginner in Open Source and would like to contribute. :)

**Comment by wouterdb** [comment]
Welcome @Aditya1402 ,

You can work on this issue, but of course you fist have to know what Inmanta is and how to run the tests.

For some introductory materials into Inmanta, take a look at the quickstart guide: https://docs.inmanta.com/community/latest/quickstart.html

For running the tests, you need to have postgresql installed on your system (because we use [pytest-postgresql](https://github.com/ClearcodeHQ/pytest-postgresql) and some form of 'make'

You can then run the test with `make install` `make test`. If this work, you can pick up this ticket, but don't be disappointed if someone else resolves the ticket first.
 
When you create a Pull Request, we will send you the CLA (contributor license agreement).

Wouter
