### ISSUE TITLE
PytestWarning: Directory not empty: 'function0'

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/inmanta-core#5675]
On inmanta-core and the extensions we regularly get the following warnings when running the test suite:

```
/home/jenkins/workspace/prove-performance-partial-export/project/inmanta-core/.tox/py39/lib/python3.9/site-packages/_pytest/pathlib.py:79: PytestWarning: (rm_rf) error removing /tmp/pytest-of-jenkins/garbage-17328e4c-5f98-41bf-bd67-79439b7b9a6d/function0
<class 'OSError'>: [Errno 39] Directory not empty: 'function0'
```

The solutions team has also been observing these issues.

Tasks:

- [ ] Investigate what causes this warning and implement a fix.

Timebox initial investigation to 1-2 hours, then report back.

**Comment by Hugo-Inmanta** [comment]
I didn't manage to get to the bottom of it after a 2 hour time box, this is what I found. (Not all of it might be 100% relevant):
- It seems the issue first arose in [Build #1602 (26 Feb 2023, 04:53:00)](https://jenkins.inmanta.com/job/core/job/inmanta-core/job/master/1602/consoleText)
- It might be caused by a bug in pytest's [rm_rf function](https://github.com/pytest-dev/pytest/blob/main/src/_pytest/pathlib.py#L147) that is supposed to "Remove the path contents recursively" ?
- I found this [recent comment](https://github.com/pytest-dev/pytest/issues/7821#issuecomment-1453939782) on a possibly related matter ?

**Comment by arnaudsjs** [comment]
This issue seems to have disappeared somewhere between the 11th and the 12th of March.
