### ISSUE TITLE
Weird error in inline if expression

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#6226]
The following model:

```
x = 1
std::print(x ? "test" : "no test")
```

produces this message:

```
Invalid value `%s`: the condition for a conditional expression must be a boolean expression (reported in <inmanta.ast.statements.generator.ConditionalExpressionResumer object at 0x7f4bb9962540> (./bug3.cf:2:12))
```

**Comment by sanderr** [comment]
So both the "%s" and the "reported in" part could be improved.

**Comment by idiotcommerce** [comment]
please mention which file this code has. then it is easy to understand and will try
thank you

**Comment by sanderr** [comment]
Let me first disclaim that this is a product backed by a company and that we're not yet at the point where we have many community contributions, so our development flow isn't really tailored to that. For example, we have a merge tool responsible for merging pull requests, which requires some additional metadata. We have not documented this procedure publicly but I can point you to another pull request for an example if you wish to go ahead with this. Apart from that, we don't really have any public documentation about setting up the development environment, though running `make install` in a new venv (preferably 3.9) should work.

If you do want to go ahead, I'll give you some pointers. This specific error is raised [here](https://github.com/inmanta/inmanta-core/blob/5dd394cf190bfe7705a1dd3bc38c5bb67fe7021a/src/inmanta/ast/statements/generator.py#L736). There is another very similar one with the same issue [here](https://github.com/inmanta/inmanta-core/blob/5dd394cf190bfe7705a1dd3bc38c5bb67fe7021a/src/inmanta/ast/statements/generator.py#L699). This second one can be reproduced by the following model.

```
typedef mytype as int matching self == (1 ? 2 : 3)

entity A:
    mytype myattr = 0
end
```

Any fixes should be accompanied by a simple test case. Conveniently, this is likely also the easiest way to verify your fix works if you're not familiar with our ecosystem. You can find an example test case [here](https://github.com/inmanta/inmanta-core/blob/5dd394cf190bfe7705a1dd3bc38c5bb67fe7021a/tests/compiler/test_conditional.py#L436).

**Comment by sanderr** [comment]
If you would like some additional documentation about our modelling language and how to use it, you could have a look at our [developer getting started guide](https://docs.inmanta.com/community/latest/model_developers/developer_getting_started.html) and our [language reference](https://docs.inmanta.com/community/latest/language.html).

**Comment by idiotcommerce** [comment]
thanks for help. i will try on this problems. thanks for reply

**Comment by sanderr** [comment]
I have just been informed by my colleagues that we do not have a contributor license agreement in place and that this may be a requirement to be able to merge community contributions. I'm afraid that the people who are in charge of this are on vacation and will be for at least two more weeks. Since I am not familiar with the legalities involved I'm afraid I dare not merge any community pull requests in the meantime, and I can not make any promises as to how they will resolve this once they're back.

I realize this may be quite off-putting. We do not mean to in any way to be closed/exclusive, but the reality at this point is that this project just doesn't have a large community presence, therefore we haven't put the effort into the contribution aspect, and I have no knowledge or authority about any of this. Either way, I thank you for your willingness to contribute, and I hope I didn't waste too much of your time.

**Comment by idiotcommerce** [comment]
very very thank you for the information. very glad to tell these details early time. 

thank you 
kancharla srinadh
