### ISSUE TITLE
Investigate performance of very large deployment

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#7262]
https://code.inmanta.com/solutions/athonet/athonet_mpn/-/merge_requests/237

**Comment by arnaudsjs** [comment]
My observations:

* The inmanta server reaches 100% CPU. Given that the server runs using a single thread, this is the maximum CPU power it can consume.
* When the low query log is enabled on PostgreSQL, it becomes clear that the queries on the `resource_persistent_state` table are particularly slow. This is strange because the query performs an update using the primary key fields of the table. Investigation of the lock state using [these queries](https://wiki.postgresql.org/wiki/Lock_Monitoring), learns us that the query is not waiting for a specific lock.

```
2024-02-23 14:27:56.536 UTC [210] LOG:  duration: 17526.568 ms  execute __asyncpg_stmt_481c0__: UPDATE public.resource_persistent_state SET last_deploy=$3,last_non_deploying_status=$4,last_success=$5,last_deployed_attribute_hash=$6,last_deployed_version=$7 WHERE environment=$1 and resource_id=$2
```
* The setup was running using the PostgreSQL JIT enabled. Disabling the JIT didn't have any significant impact on the scalability.
