### ISSUE TITLE
hasattr() doesn't work for optional relations

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta-core#7827]
In an exporter, if you want to check if an attribute or relation exists on the entity you are exporting, the easiest (and most pythonic) way is to use `hasattr(entity, "my_relation")`.  Except that it will not work in the event were the attribute is an optional relation, and its value isn't set.  That is because in that particular instance, accessing the relation raises an `OptionalValueException`, and the `DynamicProxy` class doesn't have any `__hasattr__` implementation to catch that.

It looks like an easy fix to me, but I might be missing some of the implications, which is why I don't simply go ahead with creating the patch.

**Comment by sanderr** [comment]
I disagree that `hasattr` would be appropriate here. Its purpose is to check for the existance of an attribute, not whether it's set or not. In my opinion #4972 is the real solution here.

**Comment by edvgui** [comment]
> Its purpose is to check for the existance of an attribute, not whether it's set or not.

That is what I meant here, sorry if it didn't come out clearly.  The issue is that at the moment it can't be used for that purpose.  But catching this OptionalValueException (which I would also prefer to get rid of but that is I guess a bigger change) in the `__hasattr__` would allow us to use `hasattr` for exactly that purpose.

**Comment by sanderr** [comment]
Discussed in person. Conclusion: the goal is in fact to use `hasattr` to check if a certain attribute *exists*, regardless of its value. This currently works in most cases, except when the attribute does exist but has not been set (yet?). In this case, it would be desirable that it would return `True` instead, because the attribute does exist.

Unfortunately, I don't think `__hasattr__` exists. Instead I believe `hasattr` calls into `__getattr__`, where we can't differentiate between an actual attribute access and an existence check.

**Comment by edvgui** [comment]
> Unfortunately, I don't think __hasattr__ exists. Instead I believe hasattr calls into __getattr__, where we can't differentiate between an actual attribute access and an existence check.

Damn, I didn't realize that, then I guess this can be closed in favor of the aforementioned ticket.

**Comment by sanderr** [comment]
If it's any consolation, the ticket is aimed for iso8, so while it won't be available immediately, it won't be postponed indefinitely either.
